on: [ push ]  # when will be executed

jobs:
  build:
    name: UI socks tests run (step1)  # step name
    runs-on: ubuntu-latest  # we run it on linux

    steps:
      - name: Clone repo
        uses: actions/checkout@v3 # plugin for clone repo + checkout to branch

      - name: Set up JDK 17
        uses: actions/setup-java@v3 # plugin for java setup
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Clone socks
        run: |
          git clone https://github.com/microservices-demo/microservices-demo
          ls
          pwd

      - name: Start containers
        run: |
          ls
          cd microservices-demo/deploy/docker-compose
          ls
          docker-compose -f "docker-compose.yml" up -d

      - name: Execute test with gradle
        run: |  # command to run the tests
          ./gradlew test --info

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

#      - name: Build the project
#        run: ./gradlew build --no-daemon  # command to build the project and run the tests